name: Build & Sign ZXP

on:
  workflow_dispatch:
    inputs:
      panel_path:
        description: "Path (in repo) to extension root containing CSXS/manifest.xml"
        required: true
        default: "com.sync.extension.ppro.panel"
      tsa_url:
        description: "Timestamp server URL"
        required: true
        default: "http://timestamp.digicert.com"
  push:
    tags:
      - "v*"

jobs:
  sign:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build CEP folders for all platforms
        shell: pwsh
        run: |
          # Create separate build roots for windows and mac packages
          $winRoot = "build/win"
          $macRoot = "build/mac"
          $ae_win  = Join-Path $winRoot "com.sync.extension.ae.panel"
          $pp_win  = Join-Path $winRoot "com.sync.extension.ppro.panel"
          $ae_mac  = Join-Path $macRoot "com.sync.extension.ae.panel"
          $pp_mac  = Join-Path $macRoot "com.sync.extension.ppro.panel"
          
          # Clean existing folders
          foreach ($p in @($winRoot,$macRoot,$ae_win,$pp_win,$ae_mac,$pp_mac)) {
            if (Test-Path $p) { Remove-Item $p -Recurse -Force }
          }
          
          # Create build directories
          New-Item -ItemType Directory -Force -Path $winRoot | Out-Null
          New-Item -ItemType Directory -Force -Path $macRoot | Out-Null
          
          # Helper to copy a panel skeleton
          function Copy-Panel($dest, $extSrc) {
            # Copy the extension directory structure first
            Copy-Item $extSrc $dest -Recurse
            # Then add shared files
            Copy-Item "ui" "$dest/ui" -Recurse
            Copy-Item "server" "$dest/server" -Recurse
            Copy-Item "icons" "$dest/icons" -Recurse
            Copy-Item "lib" "$dest/lib" -Recurse
            Copy-Item "bin" "$dest/bin" -Recurse
            Copy-Item "index.html" "$dest/"
            Copy-Item "host" "$dest/host" -Recurse
          }
          
          # Build Windows variants (strip darwin bins)
          Copy-Panel $ae_win  "extensions/ae-extension"
          Copy-Panel $pp_win  "extensions/premiere-extension"
          foreach ($dest in @($ae_win,$pp_win)) {
            Remove-Item "$dest/bin/darwin-arm64" -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item "$dest/bin/darwin-x64" -Recurse -Force -ErrorAction SilentlyContinue
          }
          
          # Build macOS variants (strip win bins)
          Copy-Panel $ae_mac  "extensions/ae-extension"
          Copy-Panel $pp_mac  "extensions/premiere-extension"
          foreach ($dest in @($ae_mac,$pp_mac)) {
            Remove-Item "$dest/bin/win32-x64" -Recurse -Force -ErrorAction SilentlyContinue
          }
          
          echo "Created CEP folders: $ae_win, $pp_win, $ae_mac, $pp_mac"

      - name: Fetch ZXPSignCmd
        shell: pwsh
        run: |
          git clone --depth=1 https://github.com/Adobe-CEP/CEP-Resources.git
          
          # Try multiple versions
          $versions = @("4.1.103", "4.1.102", "4.1.101", "4.1.100")
          $Exe = $null
          
          foreach ($version in $versions) {
            $testPath = "$env:GITHUB_WORKSPACE\CEP-Resources\ZXPSignCMD\$version\win64\ZXPSignCmd.exe"
            if (Test-Path $testPath) {
              $Exe = $testPath
              echo "Using ZXPSignCmd version: $version"
              break
            }
          }
          
          if (-not $Exe) { throw "ZXPSignCmd.exe not found in any version" }
          echo "ZXPSignCmd at: $Exe"
          
          # Verify executable permissions and properties
          $fileInfo = Get-Item $Exe
          echo "ZXPSignCmd file size: $($fileInfo.Length) bytes"
          echo "ZXPSignCmd last modified: $($fileInfo.LastWriteTime)"
          echo "ZXPSignCmd attributes: $($fileInfo.Attributes)"
          
          # Test ZXPSignCmd (help command always returns non-zero, that's normal)
          & $Exe -help
          echo "ZXPSignCmd help completed (exit code $LASTEXITCODE is normal)"
          # Reset error state - help command exit codes are expected
          $Error.Clear()
          $LASTEXITCODE = 0

      - name: Restore signing cert
        shell: pwsh
        run: |
          [IO.File]::WriteAllBytes("cert.p12",[Convert]::FromBase64String($env:P12_BASE64))
          $certSize = (Get-Item "cert.p12").Length
          echo "Certificate file size: $certSize bytes"
          if ($certSize -lt 1000) { throw "Certificate file too small, likely corrupted" }
          
          # Skip OpenSSL test to avoid hanging
          echo "Certificate restored successfully ($certSize bytes)"
        env:
          P12_BASE64: ${{ secrets.ZXP_P12_BASE64 }}
          ZXP_P12_PASSWORD: ${{ secrets.ZXP_P12_PASSWORD }}

      - name: Sign all ZXP packages
        shell: pwsh
        run: |
          echo "=== Starting ZXP Signing Process ==="
          $Exe = "$env:GITHUB_WORKSPACE\CEP-Resources\ZXPSignCMD\4.1.103\win64\ZXPSignCmd.exe"
          
          # Test certificate first
          echo "Certificate file exists: $(Test-Path "$env:GITHUB_WORKSPACE\cert.p12")"
          echo "Certificate size: $((Get-Item "$env:GITHUB_WORKSPACE\cert.p12").Length) bytes"
          
          # Check if CEP folders exist
          echo "AE Windows folder exists: $(Test-Path "$env:GITHUB_WORKSPACE\build\win\com.sync.extension.ae.panel")"
          echo "Premiere Windows folder exists: $(Test-Path "$env:GITHUB_WORKSPACE\build\win\com.sync.extension.ppro.panel")"
          echo "AE macOS folder exists: $(Test-Path "$env:GITHUB_WORKSPACE\build\mac\com.sync.extension.ae.panel")"
          echo "Premiere macOS folder exists: $(Test-Path "$env:GITHUB_WORKSPACE\build\mac\com.sync.extension.ppro.panel")"
          
          $certPath = "$env:GITHUB_WORKSPACE\cert.p12"
          $password = "${{ secrets.ZXP_P12_PASSWORD }}"
          
          # Define all packages to sign
          $packages = @(
            @{Input="$env:GITHUB_WORKSPACE\build\win\com.sync.extension.ae.panel"; Output="$env:GITHUB_WORKSPACE\sync-extension-ae-windows-signed.zxp"; Name="AE Windows"},
            @{Input="$env:GITHUB_WORKSPACE\build\win\com.sync.extension.ppro.panel"; Output="$env:GITHUB_WORKSPACE\sync-extension-premiere-windows-signed.zxp"; Name="Premiere Windows"},
            @{Input="$env:GITHUB_WORKSPACE\build\mac\com.sync.extension.ae.panel"; Output="$env:GITHUB_WORKSPACE\sync-extension-ae-mac-signed.zxp"; Name="AE macOS"},
            @{Input="$env:GITHUB_WORKSPACE\build\mac\com.sync.extension.ppro.panel"; Output="$env:GITHUB_WORKSPACE\sync-extension-premiere-mac-signed.zxp"; Name="Premiere macOS"}
          )
          
          # Sign each package
          foreach ($pkg in $packages) {
            echo "Signing $($pkg.Name)..."
            echo "Input: $($pkg.Input)"
            echo "Output: $($pkg.Output)"
            
            # Validate all required arguments are present
            if (-not (Test-Path $pkg.Input)) { throw "Input directory not found: $($pkg.Input)" }
            if (-not (Test-Path $certPath)) { throw "Certificate file not found: $certPath" }
            if ([string]::IsNullOrEmpty($password)) { throw "Password is empty" }
            
            echo "All required arguments validated successfully for $($pkg.Name)"
            
            # Try signing with timestamp first
            & $Exe -sign $pkg.Input $pkg.Output $certPath $password -tsa "${{ github.event.inputs.tsa_url }}"
            if ($LASTEXITCODE -ne 0) { 
              echo "$($pkg.Name) signing with timestamp failed (exit $LASTEXITCODE), trying without timestamp..."
              & $Exe -sign $pkg.Input $pkg.Output $certPath $password
              if ($LASTEXITCODE -ne 0) { throw "ZXPSignCmd failed for $($pkg.Name) with exit $LASTEXITCODE" }
            }
            echo "$($pkg.Name) signed successfully"
          }

      - name: Verify signatures
        shell: pwsh
        run: |
          $Exe = "$env:GITHUB_WORKSPACE\CEP-Resources\ZXPSignCMD\4.1.103\win64\ZXPSignCmd.exe"
          
          $zxps = @(
            "sync-extension-ae-windows-signed.zxp",
            "sync-extension-premiere-windows-signed.zxp", 
            "sync-extension-ae-mac-signed.zxp",
            "sync-extension-premiere-mac-signed.zxp"
          )
          
          foreach ($zxp in $zxps) {
            echo "Verifying $zxp..."
            & $Exe -verify "$env:GITHUB_WORKSPACE\$zxp" -certinfo
            if ($LASTEXITCODE -ne 0) { throw "$zxp verify failed" }
            echo "$zxp verified successfully"
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-zxp-packages
          path: |
            sync-extension-ae-windows-signed.zxp
            sync-extension-premiere-windows-signed.zxp
            sync-extension-ae-mac-signed.zxp
            sync-extension-premiere-mac-signed.zxp

      - name: Get tag message
        if: startsWith(github.ref, 'refs/tags/')
        id: tag_message
        shell: pwsh
        run: |
          $TAG_MESSAGE = git tag -l --format='%(contents)' ${{ github.ref_name }}
          echo "message<<EOF" >> $env:GITHUB_OUTPUT
          echo "$TAG_MESSAGE" >> $env:GITHUB_OUTPUT
          echo "EOF" >> $env:GITHUB_OUTPUT

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ${{ steps.tag_message.outputs.message }}
            
            **Downloads:**
            - After Effects: `sync-extension-ae-windows-signed.zxp` and `sync-extension-ae-mac-signed.zxp`
            - Premiere Pro: `sync-extension-premiere-windows-signed.zxp` and `sync-extension-premiere-mac-signed.zxp`
            
            Choose the appropriate package for your platform and application.
          files: |
            sync-extension-ae-windows-signed.zxp
            sync-extension-premiere-windows-signed.zxp
            sync-extension-ae-mac-signed.zxp
            sync-extension-premiere-mac-signed.zxp
          draft: false
          prerelease: false
          generate_release_notes: true