name: Build & Sign ZXP Debug

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug matrix
        run: echo "Running on ${{ matrix.os }}"
